### PR TITLE
added a screen option

### PR DESCRIPTION
**Pull request by AliMostafaRadwan**

### CODE REVIEW

**Comment by AliMostafaRadwan** [comment]
add the ability to use the screen data pip-line , forced cuda to empty cash

**Comment by AliMostafaRadwan** [comment]
(stabled) returned the web-cam code

**Comment by naseemap47** [comment]
Sorry for the late response.
Can you explain me the use case of the **screen** feature?

**Review by naseemap47 — COMMENTED** [review]
Its working good :fire:
Taking display for inference.

**Pull request closed without merging**
